---
title: "Education"
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(fontawesome)
```

#### `r fa("graduation-cap", fill = "steelblue")` __Ph.D. candidate in	Biomedical Sciences__, *current*
##### National University of Mexico ([UNAM](https://www.unam.mx/))

#### `r fa("graduation-cap", fill = "steelblue")` __Master of Science in Cell Biology__, *2016*
##### Centro de Investigaciones y Estudios Avanzados del IPN ([CINVESTAV](https://www.cinvestav.mx/))

#### `r fa("graduation-cap", fill = "steelblue")` __Bachelor in Biochemical Engineering__, *2012*
##### Escuela Nacional de Ciencias Biológicas del Instituto Politécnico Nacional ([IPN](https://www.ipn.mx/))

<br><br>


## Honors and awards



#### Ph.D. Scholarship 

Consejo Nacional de Ciencia y Tecnología (CONACYT, Mexico).

 `r fa("calendar", fill = "grey")` *2017 - current*
 
<br>

#### Graduate Student Mobility Scholarship (BECA MIXTA)  

Consejo Nacional de Ciencia y Tecnología (CONACYT, Mexico).

 `r fa("calendar", fill = "grey")` *2017*	
 
<br>

#### Master's Scholarship

Consejo Nacional de Ciencia y Tecnología (CONACYT, Mexico).

 `r fa("calendar", fill = "grey")` *2013 - 2015*	
 
<br>


#### Graduate Student Mobility Scholarship (BECA MIXTA)  

Consejo Nacional de Ciencia y Tecnología (CONACYT, Mexico).

 `r fa("calendar", fill = "grey")` *2014-2015*	

<br>


#### Summer Scholarship   

CINVESTAV

 `r fa("calendar", fill = "grey")` *2013*	

<br>


#### Undergraduate Student Mobility Award 

CINVESTAV

 `r fa("calendar", fill = "grey")` *2011*	

<br>


#### Undergraduate Scholarship   

IPN

 `r fa("calendar", fill = "grey")` *2007-2011*	

<br>

