---
title: "Experience"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    self_contained: false
---
```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(fontawesome)
```



## 	Internships



#### [__Fundazione Edmund Mach__](https://www.fmach.it/) 


Department of Bioinformatics, Marco Moretto

 `r fa("calendar", fill = "grey")` *Sep 2017 – Dic 2017*		
 
 [`r fa("thumbtack", fill = "grey")` Trento, Italy](https://goo.gl/maps/Hkd3gqxngS92)

Set non-public resource to build compendia in Mexico.

<br>  

#### [__Ontario Institute for Cancer Research__](https://oicr.on.ca/) 

 Paul C. Boutros' Laboratory 

 `r fa("calendar", fill = "grey")`*Sep 2014 – May 2016* 	
 
 [`r fa("thumbtack", fill = "grey")` Toronto, Canada](https://goo.gl/maps/JcXhPdafWg72)

Explored exon microarrays of mouse liver to characterize alternative splicing events under TCDD exposure. 

<br> 

#### [__Vancouver Prostate Center__](https://www.prostatecentre.com/)  

 Michael Cox's Laboratory
 
 `r fa("calendar", fill = "grey")` *Jun 2010 – Ago 2010*
 
 [`r fa("thumbtack", fill = "grey")` Vancouver, Canada](https://goo.gl/maps/9CuRJuufCQk)  

 Analyzed cell growth, viability, and metastasis by transfectin postate cell lines to uncover potential prostate cancer driver genes.


<br><br>

## 	Seminars, conferences and workshops


#### WGCAC Next Generation Sequencing Bioinformatics Chile 2019
 Workshop attendee
 
 `r fa("calendar", fill = "grey")` *2019*	
 
 `r fa("thumbtack", fill = "grey")`  Santiago, Chile

<br>

#### Statistical and Computational Challenges in High-Throughput Genomics with Application to Precision Medicine
Talk

 `r fa("calendar", fill = "grey")` *2018*	
 
 `r fa("thumbtack", fill = "grey")`  Oaxaca, Mexico

<br>

#### American Thoracic Society 2018, International Conference
Poster

 `r fa("calendar", fill = "grey")` *2018*	
 
 `r fa("thumbtack", fill = "grey")`  San Diego, CA

<br>  

#### International Workshops on Bioinformatics-PYTHON
Workshop attendee

 `r fa("calendar", fill = "grey")` *2017*	
 
 `r fa("thumbtack", fill = "grey")`  CCG, UNAM

<br><br>

## Teaching

#### [Ecology/R Workshop in DataCarpentry](https://map0logo.github.io/2018-08-15-puerto-rico-ecology/)
Instructor 2018

 `r fa("university", fill = "grey")`  Universidad de Puerto Rico

 `r fa("calendar", fill = "grey")` *2017*	
 
 `r fa("thumbtack", fill = "grey")`  Puerto Rico, San Juan


<br>  

#### International Workshops on Bioinformatics-GALAXY
Teacher Assistant

 `r fa("university", fill = "grey")`  Universidad Nacional Autonoma de México

 `r fa("calendar", fill = "grey")` *2017*	
 
 `r fa("thumbtack", fill = "grey")`  México, CCG




